<template>
  <f7-page name="details" class="backgriser">
    <f7-navbar title="Módulos"></f7-navbar>

    <f7-block-title>Voltajes</f7-block-title>

    <f7-block>
        <div class="data-table card">
        <table>
            <thead>
                <th>N°</th>
                <th></th>
                <th>N°</th>
                <th></th>
            </thead>
            <tbody>
                <tr>
                    <td>1:</td>
                    <td></td>
                    <td>7:</td>
                    <td></td>
                </tr>
                <tr>
                    <td>2:</td>
                    <td></td>
                    <td>8:</td>
                    <td></td>
                </tr>
                <tr>
                    <td>3:</td>
                    <td></td>
                    <td>9:</td>
                    <td></td>
                </tr>
                <tr>
                    <td>4:</td>
                    <td></td>
                    <td>10:</td>
                    <td></td>
                </tr>
                <tr>
                    <td>5:</td>
                    <td></td>
                    <td>11:</td>
                    <td></td>
                </tr>
                <tr>
                    <td>6:</td>
                    <td></td>
                    <td>12:</td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td>13:</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        </div>
    </f7-block>

    <f7-block-title>Temperaturas</f7-block-title>

    <f7-block>
        <div class="data-table card">
        <table>
            <thead>
                <th>N°</th>
                <th></th>
                <th>N°</th>
                <th></th>
            </thead>
            <tbody>
                <tr>
                    <td>1:</td>
                    <td></td>
                    <td>7:</td>
                    <td></td>
                </tr>
                <tr>
                    <td>2:</td>
                    <td></td>
                    <td>8:</td>
                    <td></td>
                </tr>
                <tr>
                    <td>3:</td>
                    <td></td>
                    <td>9:</td>
                    <td></td>
                </tr>
                <tr>
                    <td>4:</td>
                    <td></td>
                    <td>10:</td>
                    <td></td>
                </tr>
                <tr>
                    <td>5:</td>
                    <td></td>
                    <td>11:</td>
                    <td></td>
                </tr>
                <tr>
                    <td>6:</td>
                    <td></td>
                    <td>12:</td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td>13:</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        </div>
    </f7-block>

  </f7-page>
</template>
<script>
export default {
    
}
</script>
<style scoped>
</style>